test

diff --git a/.github/workflows/tf-plan-apply.yml b/.github/workflows/tf-plan-apply.yml
--- a/.github/workflows/tf-plan-apply.yml
+++ b/.github/workflows/tf-plan-apply.yml
@@ -180,12 +180,29 @@ jobs:
    #- name: Terraform Apply
    #  run: terraform apply -auto-approve tfplan
 
+    # - name: Terraform Apply
+    #   env:
+    #     TF_VAR_client_id: ${{ secrets.AZURE_PROD_CLIENT_ID }}
+    #     TF_VAR_client_secret: ${{ secrets.AZURE_PROD_CLIENT_SECRET }}
+    #   run: |
+    #     export exitcode=0
+    #     terraform apply -auto-approve tfplan || export exitcode=$?
+    #     echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+    #     if [ $exitcode -eq 1 ]; then
+    #       echo Terraform Apply Failed!
+    #       exit 1
+    #     else 
+    #       exit 0
+    #     fi
     - name: Terraform Apply
       env:
         TF_VAR_client_id: ${{ secrets.AZURE_PROD_CLIENT_ID }}
         TF_VAR_client_secret: ${{ secrets.AZURE_PROD_CLIENT_SECRET }}
       run: |
+        env | grep TF_VAR
         export exitcode=0
+        export TF_VAR_client_id="${{ secrets.AZURE_PROD_CLIENT_ID }}"
+        export TF_VAR_client_secret="${{ secrets.AZURE_PROD_CLIENT_SECRET }}"
         terraform apply -auto-approve tfplan || export exitcode=$?
         echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
         if [ $exitcode -eq 1 ]; then
@@ -194,3 +211,4 @@ jobs:
         else 
           exit 0
         fi
+  
